test_add (t02test.TestOperateCase) ... ok
test_multi (t02test.TestOperateCase) ... ok
test_divide (t02test.TestOperateCase) ... FAIL

======================================================================
FAIL: test_divide (t02test.TestOperateCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/baibianjingang/PycharmProjects/pyGreat-master/tools/testframe/unittestut/t02test.py", line 20, in inner
    ret = func(Operate)
  File "/Users/baibianjingang/PycharmProjects/pyGreat-master/tools/testframe/unittestut/t02test.py", line 65, in test_divide
    self.assertEqual(2, operator.divide())  # 错误case
AssertionError: 2 != 2.5

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
